CREATE TABLE contacts (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255),
  email varchar(255), 
  phone text,
  notes text,
  PRIMARY KEY(id)
);

INSERT INTO contacts(name, email, phone, notes) VALUES('Alex Honnold', 'freesolo@gmail.com', '555-555-5555', 'Free soloed El Capitan #sweaty palms');

INSERT INTO contacts(name, email, phone, notes) VALUES('Lynn Hill', 'womanclimber@gmail.com', '555-555-4444', 'First woman to free climb the nose route on El Capitan #badass');

INSERT INTO contacts(name, email, phone, notes) VALUES('Tommy Caldwell', 'tomster@gmail.com', '555-555-2222', 'Dawnwall Visionary climbon');

INSERT INTO contacts(name, email, phone, notes) VALUES('Adam Ondra', 'sportclimber@gmail.com', '555-555-3333', 'SportClimber Extraordinaire');

